In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_boston
dataset=load_boston()
dataset

C:\Users\dines\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
df=pd.DataFrame(dataset.data)
df

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [5]:
df.columns=dataset.feature_names
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
X=df
y=dataset.target

In [7]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [9]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=43)

In [33]:
X_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
398  38.35180   0.0  18.10   0.0  0.693  5.453  100.0  1.4896  24.0  666.0   
159   1.42502   0.0  19.58   0.0  0.871  6.510  100.0  1.7659   5.0  403.0   
12    0.09378  12.5   7.87   0.0  0.524  5.889   39.0  5.4509   5.0  311.0   
490   0.20746   0.0  27.74   0.0  0.609  5.093   98.0  1.8226   4.0  711.0   
141   1.62864   0.0  21.89   0.0  0.624  5.019  100.0  1.4394   4.0  437.0   

     PTRATIO       B  LSTAT  
398     20.2  396.90  30.59  
159     14.7  364.31   7.39  
12      15.2  390.50  15.71  
490     20.1  318.43  29.68  
141     21.2  396.90  34.41

In [34]:
X_test.head()

CRIM     ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
360  4.54192    0.0  18.10   0.0  0.770  6.398  88.0  2.5182  24.0  666.0   
391  5.29305    0.0  18.10   0.0  0.700  6.051  82.5  2.1678  24.0  666.0   
247  0.19657   22.0   5.86   0.0  0.431  6.226  79.2  8.0555   7.0  330.0   
57   0.01432  100.0   1.32   0.0  0.411  6.816  40.5  8.3248   5.0  256.0   
244  0.20608   22.0   5.86   0.0  0.431  5.593  76.5  7.9549   7.0  330.0   

     PTRATIO       B  LSTAT  
360     20.2  374.56   7.79  
391     20.2  378.38  18.76  
247     19.1  376.14  10.15  
57      15.1  392.90   3.95  
244     19.1  372.49  12.50

In [35]:
y_train

array([ 5. , 23.3, 21.7,  8.1, 14.4, 18.8, 21.1, 33.4, 17.9, 25.1, 27.5,
       12.7, 19.3, 18.3, 20.2, 20.8, 15.2,  7.2, 26.2, 21.7, 16.4,  8.8,
       21. , 24.8, 22.8, 31.1,  5. , 24.6, 30.5, 19.6, 21.2, 20.3, 20.6,
       23.2, 19.7, 50. , 13.8, 26.6, 19.5, 22.8, 23.1,  8.5, 29.9, 20.6,
       12.7, 24. , 23.1, 19.5, 21.7, 31.7, 29.6, 20. , 19.1, 23.7, 43.1,
       28.7, 15.2,  8.3,  9.7, 21.8, 16.6, 23.9, 27.1, 22.6, 19.1, 22.2,
       19.3, 50. , 15.1, 24.1, 37.9, 21.2, 32.5, 13.3, 10.2, 19.3, 25. ,
       46.7, 17.2, 17.4, 48.5, 15.6, 14.3, 23.7, 23.8, 14.1, 17.4, 19. ,
       21.8, 50. , 22.9, 34.9, 24.3, 22.2, 21.6, 26.4, 19.5, 18.5, 19.9,
       31.2, 20.4, 17.2, 19.6, 19.4, 24.7, 22.6, 20.6, 18.2, 23.5, 23.2,
       21. , 18.4, 18.9, 33.8, 38.7, 19.3, 21.7, 18.7, 22.2, 31. , 44. ,
       30.7, 20.6, 12.7, 20.6, 16.6, 15. , 19.4, 22.4, 50. , 22.1, 15.4,
       21.5, 21.4, 20. , 20.5, 26.5, 16.1, 12.5, 50. , 18.4, 21. , 22.6,
       20.3, 14.4, 31.5, 34.7, 18.3, 15.3, 31.5, 11

In [36]:
y_test

array([25. , 23.2, 20.5, 31.6, 17.6, 19.7, 18.5, 22.2, 22.7, 23.7, 22.8,
       24.8, 17.5, 21.7, 21.4,  5.6, 29. , 37.2, 14.9, 50. , 22. ,  7.2,
       19. , 35.4, 10.4, 29.8, 16.7, 19.2, 19.9, 14.6, 21.1, 19.2, 10.9,
        6.3, 24.3, 18.6, 17.2, 20.9, 23.3, 25.2, 21.5, 10.2, 25. , 14.1,
       37.6, 18.7, 23.1, 17.4, 35.2, 15.4, 24.5, 48.3, 39.8, 24.7, 13.6,
       50. , 50. , 24.8, 28.6, 22. , 21.4, 14.8, 21.6, 22.3, 30.1, 13.4,
       24.4, 33.3,  8.7, 21.4, 15.7,  8.4,  8.5, 13.8,  7. , 22. , 24. ,
       20.1, 17.8, 10.4, 12.8, 19.3, 14. ,  7.2, 22.5, 30.1, 11.5, 36. ,
       13.4, 15.6, 17.8, 24.5, 22. , 23. , 18.9, 16.8, 41.3, 25. , 33. ,
       43.8, 16.2, 19.6])

In [31]:
from xgboost import XGBClassifier,XGBRegressor
xg=XGBRegressor(learning_rate=0.1)
xg.fit(X_train,y_train)
y_pred=xg.predict(X_test)

In [37]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
r2_score(y_pred,y_test)

0.8439710439836013

In [38]:
mean_squared_error(y_pred,y_test)

13.269655726391226

In [39]:
mean_absolute_error(y_pred,y_test)

2.3837427784414853